# Required metadata
sonar.projectKey=PowerFleet-IMS
sonar.projectName=PowerFleet IMS

# Where is the source code? (Usually 'src')
sonar.sources=src

# Exclude test files, node_modules, and build outputs from the main scan
sonar.exclusions=node_modules/**, dist/**, build/**, **/*.spec.ts, **/*.test.ts

# Optional: If you have a separate folder for tests, define it here
# sonar.tests=tests