# Required metadata
sonar.projectKey=PowerFleet-IMS
sonar.projectName=PowerFleet IMS
sonar.organization=Mohamed ElAnani

# Where is the source code?
sonar.sources=app,db,lib,middleware

# Exclude test files, node_modules, and build outputs from the main scan
sonar.exclusions=node_modules/**, dist/**, build/**, **/*.spec.ts, **/*.test.ts, test/**

# Optional: If you have a separate folder for tests, define it here
# sonar.tests=tests